language: node_js
node_js:
  - "10"
dist: trusty
os: linux
services:
  - redis-server
addons:
  - rethinkdb
install:
  - yarn --cwd client install;
  - yarn --cwd server install;
script:
  - yarn --cwd client test;
  - yarn --cwd server test;