language: node_js
node_js:
  - "10"
dist: trusty
os: linux
services:
  - redis-server
addons:
  rethinkdb: '2.3.6'
before_script:
  - rethinkdb --daemon
cache:
  directories:
    - server/node_modules
    - client/node_modules
install:
  - yarn --cwd client install
  - yarn --cwd server install
script:
  - yarn --cwd client test
  - yarn --cwd server test